# Generated by Django 6.1.1 on 2026-09-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id_user"]},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
