# Generated by Django 6.1.1 on 2026-09-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ride",
            options={"ordering": ["-id_ride"]},
        ),
        migrations.AlterModelOptions(
            name="rideevent",
            options={"ordering": ["created_at"]},
        ),
    ]
