# Generated by Django 6.1.1 on 2026-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_alter_ride_options_alter_rideevent_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="pickup_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("en-route", "En Route"),
                    ("pickup", "Pickup"),
                    ("dropoff", "Dropoff"),
                ],
                db_index=True,
                default="pickup",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="rideevent",
            index=models.Index(
                fields=["id_ride", "created_at"], name="id_ride_created_at_idx"
            ),
        ),
    ]
